# Generated by Django 4.2.2 on 2023-06-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0016_auto_20190401_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.CharField(max_length=2000),
        ),
    ]
