# Generated by Django 4.2.2 on 2023-06-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0017_alter_prescription_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.CharField(max_length=2000),
        ),
    ]
