# Generated by Django 4.2.2 on 2023-06-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0019_alter_prescription_doctor_alter_prescription_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='PrescribingPatient',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribingDoctor',
            field=models.CharField(default=' ', max_length=2000),
            preserve_default=False,
        ),
    ]
