# Generated by Django 4.2.2 on 2023-06-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0021_rename_prescribingpatient_prescription_prescribingpatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='prescribingDoctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescribingPatient',
        ),
    ]
