# Generated by Django 4.2.2 on 2023-06-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0022_remove_prescription_prescribingdoctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescribingDoctor',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribingPatient',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
