# Generated by Django 4.2.2 on 2023-07-05 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0023_prescription_prescribingdoctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=2000)),
                ('notes', models.TextField()),
                ('appointmentpatient', models.CharField(default='', max_length=2000)),
                ('appointmentdoctor', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
