# Generated by Django 4.2.2 on 2023-07-11 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0024_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='AppointmentTimeStamp',
            field=models.DateTimeField(auto_now_add=True, default='1994-11-27'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
